// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB96CHrBMnaO8olo9fKnovF4umCh71uz2o',
    appId: '1:235369538704:web:8cdfce1e0509529a6b2415',
    messagingSenderId: '235369538704',
    projectId: 'fcm-test3-6d114',
    authDomain: 'fcm-test3-6d114.firebaseapp.com',
    databaseURL: 'https://fcm-test3-6d114-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fcm-test3-6d114.appspot.com',
    measurementId: 'G-EB88D3RFB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD32kpp3pMdNOXVDkOimMX-WEcJ83sbv9w',
    appId: '1:235369538704:android:c1c4794ca33a535f6b2415',
    messagingSenderId: '235369538704',
    projectId: 'fcm-test3-6d114',
    databaseURL: 'https://fcm-test3-6d114-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fcm-test3-6d114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOT4-8XLuIbcTGbB8i0WIj1t8iaCc-GIQ',
    appId: '1:235369538704:ios:8de6de2b484b11d86b2415',
    messagingSenderId: '235369538704',
    projectId: 'fcm-test3-6d114',
    databaseURL: 'https://fcm-test3-6d114-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fcm-test3-6d114.appspot.com',
    iosClientId: '235369538704-a3j5vnnnkdibto3r09p6e5sf66behj7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.deanora',
  );
}
